### ISSUE TITLE
dinucleotide_frequencies

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#14] opened 2019-08-22 14:37 UTC
where it at

**Comment by rpolicastro** [comment] 2019-08-23 15:15
The function works for me. Can you reproduce it?

**Comment by gzentner** [comment] 2019-11-06 15:03
This is what I'm seeing:

```
> frequencies <- dinucleotide_frequencies(exp, genome_assembly = assembly, threshold = 3)
Error in dinucleotide_frequencies(exp, genome_assembly = assembly, threshold = 3) : 
  could not find function "dinucleotide_frequencies"
> 
> p <- plot_dinucleotide_frequencies(frequencies, ncol = 3) +
+     ggplot2::theme(text = element_text(size = 6))
Error in eval(lhs, parent, parent) : object 'frequencies' not found
```

**Comment by rpolicastro** [comment] 2019-11-06 19:44
I fixed an error in the plotting function. Check to see if this commit fixes your problem.

https://github.com/rpolicastro/tsrexplorer/commit/ff6ac04bcbd62b644233bbfba25883513258780d

**Comment by rpolicastro** [comment] 2019-11-11 22:41
seems to have been fixed by updating conda

**Closed by rpolicastro** 2019-11-11 22:41 UTC
Labels: bug
